media:
  input: public/images
  output: /images
content:
  - name: portfolio
    label: Portfolio Pieces
    path: src/content/portfolio
    filename: "{year}-{month}-{day}-{fields.title}.md"
    type: collection
    fields:
      - name: title
        type: string
      - name: description
        type: string
      - name: image
        type: image
      - name: publishDate
        type: date
